### PR TITLE
feature: allow default index configuration

### PR DESCRIPTION
**Pull request by mvisonneau**
This change provides configuration capability of a default index.

### CODE REVIEW

**Comment by ktr0731** [comment]
Thanks for submitting a PR.

I have some concerns about this feature.
First, about use-cases. Could you tell me about it?
Second, about the increasing complexity of go-fuzzyfinder by adding this feature. This is mostly the same as [fzf's discussion](https://github.com/junegunn/fzf/issues/883#issuecomment-289061692).

**Comment by mvisonneau** [comment]
👋 hey @ktr0731, I understand your concerns.

I implemented it yesterday in this project : https://github.com/mvisonneau/vac/blob/master/cmd/switch.go#L39, I just made an asciinema to have some visibility around the usecase : https://asciinema.org/a/343653

**Comment by ktr0731** [comment]
Sorry, I don't have much time to check the issue, I'll check it over the weekend!

**Comment by ktr0731** [comment]
`WithDefaultIndex` looks good, but it doesn't work as expected when specified with `WithHotReload` option.
For example, we assume that we specify `WithDefaultIndex(10)` and the number of rows in initial input is 5. And after that, 7 lines are provided. Now, The number of rows is 12, but `go-fuzzyfinder` points to line 5, not line 10 because of initial input less than 10 lines.
Options that don't work as expected under certain conditions can be very confusing to users. So, we can't provide `WithDefaultIndex`.

Thanks for proposing a new feature.

**Pull request closed without merging**
