### PR TITLE
[retry] Replace termbox to tcell

### PR DESCRIPTION
**Pull request by tjmtmmnk**
related: #32 

Hello.

Finally, tcell announced the fix of lost key problem officially. https://github.com/gdamore/tcell/issues/194#issuecomment-782751304

So, we can avoid the workaround which causes the cgo problem!

I could confirm that [this program](https://github.com/ktr0731/go-fuzzyfinder/issues/17#issue-600536866) work well in local.

### CODE REVIEW

**Comment by ktr0731** [comment]
@tjmtmmnk 
Hi, thanks for reporting the bug is fixed!
I don't have much time to spend on this right now, so can you please wait a little while?
I'll probably be able to review this PR in a few days...

**Comment by ktr0731** [comment]
It looks like there are conflicts, so can you resolve them?

**Comment by tjmtmmnk** [comment]
Of course, any time is ok!

**Review by ktr0731 — COMMENTED** [review]
I tried another snippet, but it got strange behavior. The second prompt didn't appear.
https://github.com/ktr0731/go-fuzzyfinder/issues/46

It seems that `PollEvent` is returning nil because the `Screen` is finalized in the previous session.

**Comment by tjmtmmnk** [comment]
I cloud reproduce the same problem...
I'm getting a little busy too so it may take some time to investigate🙇‍♂️

**Comment by ktr0731** [comment]
No problem 👍

**Comment by tjmtmmnk** [comment]
Hello, I apologize for the delay.

After checking, [this problem](https://github.com/ktr0731/go-fuzzyfinder/issues/46#issue-787155088) seems to be caused by a package variable `defaultFinder`.

`defaultFinder` was singleton, so `finder.term` was `nil` in the first `Find` but `finder.term` was `not nil` in the second `Find`.

Therefore, I created `newFinder` func to recreate `finder` every time you exec `Find`.

I could confirm that [this problem](https://github.com/ktr0731/go-fuzzyfinder/issues/46#issue-787155088) was fixed in local.

---

I tried to add test, but `finder` is [recreated in test](https://github.com/ktr0731/go-fuzzyfinder/blob/master/helper_test.go#L5) so it was difficult to check.

**Review by ktr0731 — APPROVED** [review]
Perfect! Looks good to me, thanks for your continuous contribution!

**Pull request merged**
